// Generated by Wrangler by running `wrangler types --env-interface Env`

interface Env {
	MY_KV: KVNamespace;
	ENVIRONMENT: "production" | "development";
	LOG_LEVEL: "info" | "debug";
	MY_BUCKET: R2Bucket;
	HYPERDRIVE: Hyperdrive;
}
