import { Context, Layer } from "effect"

/**
 * CloudflareBindings Service
 *
 * Provides access to Cloudflare's env object and ExecutionContext.
 * This is the foundation layer for all other services.
 *
 * The `Env` type is automatically generated by Wrangler from wrangler.toml.
 * Run `pnpm wrangler types` to regenerate worker-configuration.d.ts.
 *
 * **Why This Exists**:
 * - Cloudflare bindings are only available at request time
 * - We need to inject them into Effect's layer system
 * - Provides type-safe access to bindings throughout the application
 */
export class CloudflareBindings extends Context.Tag("CloudflareBindings")<
  CloudflareBindings,
  {
    readonly env: Env
    readonly ctx: ExecutionContext
  }
>() {
  /**
   * Creates a CloudflareBindings layer from env and ctx
   *
   * This should be called once per request with the env and ctx
   * parameters passed to your fetch handler.
   */
  static layer(env: Env, ctx: ExecutionContext) {
    return Layer.succeed(this, { env, ctx })
  }
}
