import { Context, Effect } from "effect"

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// CloudflareEnv - Request-scoped environment bindings
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/**
 * CloudflareEnv Service
 *
 * Provides access to Cloudflare's env object containing bindings.
 * This is provided per-request via Effect.provideService.
 *
 * The `Env` type is automatically generated by Wrangler from wrangler.toml.
 * Run `pnpm cf-typegen` to regenerate worker-configuration.d.ts.
 */
export class CloudflareEnv extends Context.Tag("CloudflareEnv")<
  CloudflareEnv,
  { readonly env: Env }
>() {}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// CloudflareCtx - Request-scoped execution context
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/**
 * CloudflareCtx Service
 *
 * Provides access to Cloudflare's ExecutionContext.
 * This is provided per-request via Effect.provideService.
 *
 * Use this to access ctx.waitUntil() for background tasks.
 */
export class CloudflareCtx extends Context.Tag("CloudflareCtx")<
  CloudflareCtx,
  { readonly ctx: ExecutionContext }
>() {}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Helper Effects
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/**
 * Schedule a background task that runs after the response is sent.
 *
 * @example
 * ```typescript
 * yield* waitUntil(
 *   Effect.log("This runs in the background")
 * )
 * ```
 */
export const waitUntil = <A, E>(effect: Effect.Effect<A, E>): Effect.Effect<void, never, CloudflareCtx> =>
  Effect.gen(function* () {
    const { ctx } = yield* CloudflareCtx
    ctx.waitUntil(
      Effect.runPromise(
        effect.pipe(
          Effect.tapErrorCause(Effect.logError),
          Effect.catchAll(() => Effect.void)
        )
      )
    )
  })
